services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik-minimal.yml:/etc/traefik/traefik.yml
    networks:
      - sharednet

  ui:
    build: ./ui
    container_name: ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`localhost`)"
      - "traefik.http.services.ui.loadbalancer.server.port=80"
    networks:
      - sharednet

networks:
  sharednet:
    driver: bridge
